### PR TITLE
WIP: Make the default cfg file more general

### PR DESCRIPTION
**Pull request by isolovey-robarts**
- Just an idea for a generic `graham.cfg`
- updated `graham-khanlab.cfg`

### CODE REVIEW

**Comment by akhanf** [comment]
made a couple minor fixes.. wonder if there is also a nicer way to select the custom config? right now users would have to edit line 34 of 00_init.sh, which is not the most intuitive.. especially since all of my lab would need to switch to graham-khanlab.cfg to avoid breaking things.. any thoughts?

**Comment by isolovey-robarts** [comment]
Maybe have a setup script, e.g. `setup.sh`, that sources the variables in `00_init.sh` and loads the singularity module? I've added a "profile",  `=default` by default, or specified on the command line, `setup.sh khanlab`.

**Comment by isolovey-robarts** [comment]
Renamed default file back to `graham.cfg` to avoid breaking everyone's existing setup.

It still needs work though, because the allocation in `graham.cfg` has changed from `khanlab`'s allocation to a `def-` allocation of the user... 

If we push this to master, I think everyone will have to re-run `setup.sh` with the right argument (either `khanlab`, `bmi`, or nothing). After removing the already inserted lines in `~/.bash_profile`.

**Comment by akhanf** [comment]
almost there! @isolovey-robarts can you try the following after a fresh setup? (with and without khanlab) and let me know where your container ends up? `singularity run docker://poldracklab/mriqc:latest`

**Comment by akhanf** [comment]
mriqc is actually pretty big, may just do docker://bids/example for the demo instead

**Comment by isolovey-robarts** [comment]
The setup seems to work fine. However, running `singularity run docker://bids/example` produces a whole bunch of warnings, then an error in the end:

```
>singularity run docker://bids/example
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
```
...
```
2019/10/01 11:15:24  warn xatt{usr/lib/node_modules/bids-validator/node_modules/readable-stream/float.patch} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2019/10/01 11:15:24  warn xatt{usr/lib/node_modules/bids-validator/node_modules/readable-stream/lib} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2019/10/01 11:15:24  warn xatt{usr/lib/node_modules/bids-validator/node_modules/readable-stream/lib/_stream_duplex.js} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
```
...
```
ERROR:   build: failed to make environment files: open /scratch/isolovey/sbuild-160446513/fs/etc/resolv.conf: permission denied
FATAL:   Unable to handle docker://bids/example uri: unable to build: packer failed to pack: while inserting base environment: build: failed to make environment files: open /scratch/isolovey/sbuild-160446513/fs/etc/resolv.conf: permission denied
```

It also takes ~10 minutes.

**Comment by akhanf** [comment]
since module load singularity resets SINGULARITY_TMPDIR to /scratch (and causes pull failures), moved module load to occur before init, and set SINGULARITY_TMPDIR to /tmp in the cfg file

**Pull request merged**
